sudo: required

language: generic

services:
 - docker
 
before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t cheonylee/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true cheonylee/docker-react-app npm run test -- --coverage

after_success:
 - echo "test sucssees"